import { Bell, Check, Coffee, Flame, Pause, Play, RotateCcw, Sparkles, Square } from 'lucide-react'
import { usePomodoro } from '../contexts/PomodoroContext'

function formatTime(milliseconds: number) { const seconds = Math.ceil(milliseconds / 1000); return `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}` }

export default function PomodoroState() {
  const timer = usePomodoro()
  const progress = Math.max(0, Math.min(100, 100 - timer.remainingTime / (timer.duration || 1) * 100))
  const status = timer.mode === 'BREAK' ? 'GIỜ NGHỈ' : timer.status === 'COMPLETED' ? 'HOÀN THÀNH' : timer.status === 'PAUSED' ? 'ĐANG TẠM DỪNG' : 'TẬP TRUNG'
  return <div className="page focus-page"><div className="page-title-row"><div><span className="section-kicker">GLOBAL FOCUS SERVICE</span><h1>Thời gian tập trung</h1><p className="subtext">Timer tiếp tục chạy ngay cả khi bạn chuyển sang AI Tutor hoặc Roadmap.</p></div><div className="focus-streak"><Flame size={20} fill="currentColor" /><strong>7</strong><span>ngày liên tiếp</span></div></div><div className="focus-layout"><section className={`timer-panel state-${timer.status.toLowerCase()}`}><div className="mode-tabs"><button className={timer.mode !== 'BREAK' ? 'active' : ''}><Sparkles size={13} /> Tập trung</button><button className={timer.mode === 'BREAK' ? 'active' : ''}><Coffee size={13} /> Nghỉ</button></div><div className="timer-state-label"><span>{timer.mode === 'BREAK' ? <Coffee size={17} /> : timer.status === 'COMPLETED' ? <Check size={17} /> : <Bell size={17} />}</span>{status}</div><div className="timer-ring" style={{ '--progress': `${progress}%` } as React.CSSProperties}><div><span>{formatTime(timer.remainingTime)}</span><small>{timer.isRunning ? `Phiên ${timer.currentSession} / ${timer.totalSessions}` : timer.status === 'COMPLETED' ? 'Chu kỳ đã hoàn tất' : 'Sẵn sàng bắt đầu'}</small></div></div><div className="timer-actions"><button className="reset-btn" onClick={timer.reset}><RotateCcw size={17} /> Đặt lại</button>{timer.isRunning ? <button className="primary-btn large" onClick={timer.pause}><Pause size={17} fill="currentColor" /> Tạm dừng</button> : <button className="primary-btn large" onClick={() => timer.start()}><Play size={17} fill="currentColor" /> {timer.status === 'COMPLETED' ? 'Bắt đầu lại' : 'Bắt đầu'}</button>}{timer.isRunning && <button className="stop-btn" onClick={timer.stop}><Square size={16} fill="currentColor" /> Kết thúc</button>}</div>{timer.linkedLesson && <div className="timer-notice">📚 Đang học: {timer.linkedLesson}</div>}<div className="timer-presets"><span>Thời lượng:</span>{[25, 50, 90].map((value) => <button key={value} onClick={() => timer.setDurations(value, 5)}>{value} phút</button>)}</div></section><aside className="focus-side"><div className="focus-note"><div className="note-icon"><Sparkles /></div><strong>Một timer cho cả hành trình</strong><p>Chuyển trang thoải mái. Mimo sẽ giữ đúng thời gian bằng timestamp và khôi phục sau khi reload.</p></div><div className="session-card"><div className="section-head"><h3>Hôm nay</h3><span>{timer.sessionCount} phiên</span></div><div className="session-number"><strong>{Math.round(timer.todayFocusTime / 60)} phút</strong><span>thời gian tập trung đã ghi nhận</span></div><div className="session-bar"><b style={{ width: `${Math.min(100, timer.sessionCount / timer.totalSessions * 100)}%` }} /></div><div className="session-meta"><span><Check size={15} /> {timer.sessionCount} / {timer.totalSessions} phiên</span><span>+{timer.sessionCount * 25} XP</span></div></div></aside></div></div>
}
